version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
   
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  users_service:
    build: ./users 
    volumes:
      - ./users:/var/www/html
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    depends_on:
      - rabbitmq

  notifications_service:
    build: ./notifications  
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
