framework:
  messenger:
    transports:
      # Define the transport that communicates with RabbitMQ
      external_messages:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          auto_setup: false
          exchange:
            name: user_registration_exchange # Match the exchange name used in the users app
            type: direct
          queues:
            user_registration_queue: # Define the queue name
              binding_keys: [user_registration] # Optional, depending on your routing setup in RabbitMQ

    routing:
      # Route the UserRegisteredEvent messages to the external_messages transport
      'App\Domain\User\Events\UserRegisteredEvent': external_messages
